k8s_masters:
  hosts:
    # Control nodes
    node1.dev-o.de:
      ansible_host: 192.168.0.11
    node2.dev-o.de:
      ansible_host: 192.168.0.12
    node3.dev-o.de:
      ansible_host: 192.168.0.13
k8s_workers:
  hosts:
    # Worker nodes
    node4.dev-o.de:
      ansible_host: 192.168.0.14
    node5.dev-o.de:
      ansible_host: 192.168.0.15
    node6.dev-o.de:
      ansible_host: 192.168.0.16
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
