kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-client
    #  annotations:
    #    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
